name: Github Actions 
run-name: Github Action learning workflow

on: 
 workflow_dispatch:
   inputs:
     app_id:
       type: string
jobs:
  test-job:
   runs-on : ubuntu-latest
   steps:
    - name: checkout the code 
      uses: actions/checkout@v4
      with:
        node-version: 24
    - name: Install npm packages
      run: npm ci
    - name: execute playwright tests
      run: |
        npx playwright test
    - name: Log messages
      continue-on-error: true
      run: |
        echo "### Welcome to github actions :rocket: " >> $GITHUB_STEP_SUMMARY"
            
